version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - cache_network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27018:27017"
    networks:
      - cache_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  cache_network:
    driver: bridge
