services:
  service:
    build:
      context: .
    secrets:
      - postgres-password
    ports:
      - 8030:8030
    depends_on:
      postgres:
          condition: service_healthy
  
  postgres:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - postgres-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_USER_PASSWORD=${POSTGRES_PASSWORD}

      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password # password for superuser (postgres)
    # expose:
    #   - 5432
    ports:
    - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
secrets:
  postgres-password:
    file: secrets/postgres/password.txt
